spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.6:3306/tiktok-user
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 12000
logging:
  level:
    com.atguigu.gulimall: debug
