spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.6:3306/tiktok-video
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: tiktok-video
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 13000
logging:
  level:
    com.atguigu.gulimall: debug
