spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.6:3306/tiktok-product
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: tiktok-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 11000
logging:
  level:
    com.cdut.tiktok: debug
